# Generated by Django 3.2.9 on 2021-11-08 00:38

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=140, null=True)),
                ('city', models.CharField(blank=True, max_length=140, null=True)),
                ('state', models.CharField(blank=True, max_length=140, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.images')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(to='data.Images')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySpaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('property', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='data.properties')),
                ('tasks', models.ManyToManyField(to='data.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='', verbose_name=data.models.Images)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.properties')),
                ('property_space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.propertyspaces')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('images', models.ManyToManyField(to='data.Images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.projects')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyItems',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.properties')),
                ('tasks', models.ManyToManyField(to='data.Tasks')),
            ],
        ),
    ]
