# Generated by Django 3.2.9 on 2021-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyspaces',
            name='tasks',
            field=models.ManyToManyField(null=True, to='data.Tasks'),
        ),
    ]
