# Generated by Django 3.2.9 on 2021-11-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_propertyspaces_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachments',
            name='images',
            field=models.ManyToManyField(blank=True, to='data.Images'),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='images',
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(blank=True, to='data.Images'),
        ),
        migrations.AlterField(
            model_name='propertyitems',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='data.Tasks'),
        ),
        migrations.AlterField(
            model_name='propertyspaces',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='data.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='images',
            field=models.ManyToManyField(blank=True, to='data.Images'),
        ),
    ]
