# Generated by Django 3.2.9 on 2021-11-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_propertyspaces_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('pl', 'Planning'), ('ns', 'Not Started'), ('ip', 'In Progress'), ('cm', 'Completed'), ('hl', 'On Hold')], default='pl', max_length=2),
        ),
    ]
