# Generated by Django 3.2.9 on 2021-11-08 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_alter_projects_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='shared_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='propertyspaces',
            unique_together={('property', 'name')},
        ),
    ]
