# Generated by Django 3.2.9 on 2021-11-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_properties_thumbnail'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='properties',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_property'),
        ),
    ]
