# Generated by Django 3.2.9 on 2021-11-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_properties_unique_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('property', 'property_space', 'name')},
        ),
    ]
