# Generated by Django 3.2.9 on 2021-11-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_projects_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='property_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.propertyspaces'),
        ),
    ]
