# Generated by Django 3.2.9 on 2021-11-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_projectactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='action_items',
            field=models.ManyToManyField(blank=True, to='data.ProjectActionItem'),
        ),
    ]
