# Generated by Django 3.2.9 on 2021-12-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_properties_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyspaces',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
