# Generated by Django 3.2.9 on 2021-12-11 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0016_auto_20211206_2017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='data.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pl', 'Planning'), ('ns', 'Not Started'), ('ip', 'In Progress'), ('cm', 'Completed'), ('hl', 'On Hold')], default='pl', max_length=2)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('action_items', models.ManyToManyField(blank=True, to='project.ProjectActionItem')),
                ('images', models.ManyToManyField(blank=True, to='data.Images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.properties')),
                ('property_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.propertyspaces')),
                ('shared_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'property_space', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('images', models.ManyToManyField(blank=True, to='data.Images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects')),
            ],
        ),
    ]
