# Generated by Django 3.2.9 on 2021-12-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachments',
            name='type',
            field=models.CharField(choices=[('db', 'DropBox'), ('od', 'OneDrive'), ('sp', 'SharePoint'), ('gd', 'GoogleDrive'), ('wa', 'URL'), ('im', 'Image')], default='wa', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectattachments',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectattachments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
