# Generated by Django 3.2.9 on 2021-12-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_addprojectmaterials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProjectMaterials',
            new_name='ProjectMaterials',
        ),
    ]
