# Generated by Django 3.2.9 on 2021-12-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211219_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactionitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectactionitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectactionitem',
            name='status',
            field=models.CharField(choices=[('pl', 'Planning'), ('ns', 'Not Started'), ('ip', 'In Progress'), ('cm', 'Completed'), ('hl', 'On Hold')], default='pl', max_length=2),
        ),
    ]
